name: Test imap_processing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install combined environment
        run: uv sync --group test

      - name: Test imap_processing
        run: uv run --frozen pytest --rootdir=. --confcutdir=. -c imap_processing/pyproject.toml --import-mode=importlib imap_processing/imap_processing/tests
