name: Test imap_L3_processing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install combined environment
        run: uv sync --group test

      - name: Setup git LFS for imap_L3_processing
        working-directory: imap_L3_processing
        run: |
          git lfs install
          git lfs pull

      - name: Test imap_L3_processing
        run: uv run --frozen python -m unittest discover -s imap_L3_processing/tests
